// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVOxJwaaAgQ-1z6hGmvZpTFe_fk6W2VAo',
    appId: '1:875651930056:web:ecd14060c49977c66d52fd',
    messagingSenderId: '875651930056',
    projectId: 'journal-app-203e0',
    authDomain: 'journal-app-203e0.firebaseapp.com',
    storageBucket: 'journal-app-203e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeWYz5uavRAOHHUednAcxk3mi4n8ZLq2o',
    appId: '1:875651930056:android:63b3098f1246eb4d6d52fd',
    messagingSenderId: '875651930056',
    projectId: 'journal-app-203e0',
    storageBucket: 'journal-app-203e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBugUG5bvzpxNTFuXA_RRcu2cUqnwx8kJo',
    appId: '1:875651930056:ios:d66976d351c2de8e6d52fd',
    messagingSenderId: '875651930056',
    projectId: 'journal-app-203e0',
    storageBucket: 'journal-app-203e0.appspot.com',
    iosClientId: '875651930056-35m541m9n9tkq4m0cng0p61a93g3cs6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.journalApp4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBugUG5bvzpxNTFuXA_RRcu2cUqnwx8kJo',
    appId: '1:875651930056:ios:d66976d351c2de8e6d52fd',
    messagingSenderId: '875651930056',
    projectId: 'journal-app-203e0',
    storageBucket: 'journal-app-203e0.appspot.com',
    iosClientId: '875651930056-35m541m9n9tkq4m0cng0p61a93g3cs6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.journalApp4',
  );
}
